### ISSUE TITLE
Regenerating the test data for the integration tests should be trivial

### ISSUE THREAD

**Issue by csomh** [packit/ogr#445]
After the Packit organisation rename, I had to regenerate the test data for GitHub. This proved to be a considerable effort, with roughly the following steps:

- create a Python virtualenv and install test dependencies - this needed several attempts, to get it right.
- clean up test data for GitHub
- set my GitHub API token
- run the tests with `make check` only to realise that the `GITHUB_APP_ID` and the `GITHUB_APP_PRIVATE_KEY_PATH` env vars were not set. Ask by the team how what values to set these (stage is fine) and run the tests again.
- Start following comments left in individul tests, to manually bring the repos, PRs, issues in the state the state expected them to be. For this I had to run the tests over and over again, see a test fail, inspect the failure to figure out the reason, fix the pre-conditions and run the tests again to check that the fix worked.

The above is extremely tedious and frustrating.

Regenerating test data should be trivial, for example:

- if credentials are needed, the contribution guide should explicitly call those out with clear indication what their values/credentials should be.
- they should be checked to be set even before starting any test run.
- pre-conditions for tests should be checked, and preferably automatically set up given the credentials above, without requiring any manual action.
- if it's still required to set pre-conditions manually, these steps should be clearly called out with detailed instructions in the contribution guide.

**Comment by lachmanfrantisek** [comment]
Much better since the last test rework but still not ideal. This is more an epic than a single issue.

**Comment by lachmanfrantisek** [comment]
What about spending some on it before Xmas, @mfocko , @jscotka ?

**Comment by mfocko** [comment]
still needed

**Comment by lachmanfrantisek** [comment]
Still would be nice to improve.

**Comment by lachmanfrantisek** [comment]
Since this still looks more like an epic, let's take a look at the current state and the real issues:

> * if credentials are needed, the contribution guide should explicitly call those out with clear indication what their values/credentials should be.

It's there. I don't think we need to describe what `GITHUB_TOKEN` is, but if you feel this is needed, we can add a sentence about that.

> * they should be checked to be set even before starting any test run.

I would say they are checked before the test when we are in the write mode. And users get an exception when the token is not set. I donẗ think we need to change anything here.

> * pre-conditions for tests should be checked, and preferably automatically set up given the credentials above, without requiring any manual action.

:+1: for checking the prerequisites -- I think we do that already but there is no unified way and it behaves like a real test failure what I don't like. We can raise a specific exception (can mention manual steps if needed) or do this in some fixture.

Setting everything up automatically is tricky. The problem is that we need a dedicated setup for each test case and it's hard (AFAIK) to run it outside of the test (=in the setup phase):
* Cover by a specific exception so we can clearly see it's outside of the test itself.
* Provide per-test fixture with the setup.
* Any better idea?

> * if it's still required to set pre-conditions manually, these steps should be clearly called out with detailed instructions in the contribution guide.

Prerequisites differ between test cases. It can't be documented in the contribution guide -- but it can be clearly stated in the doc-string of the test method and/or in the exception when the condition is not met => this general rule can be added to the contribution guide and/or the PR template.

----

So to conclude, if you agree, I would create issues for the following:
* [ ] 1. document and unify the checking of the prerequisites of the test cases
* [ ] 2. document and unify, how we want to manage test prerequisites
  * [ ] how to manage this for those that we can automate
  * [ ] how this will be documented for manual ones


(We need to agree on the way we want this.)

ping @mfocko and @jscotka

**Comment by mfocko** [comment]
I think the fixtures (with both prepare and clean up) would be nice, even though it introduces dependencies into test, e.g. `project_create` must be functional for tests that require playground :shrug:
