### ISSUE TITLE
Refactor exceptions for non-supported features

### ISSUE THREAD

**Issue by mfocko** [packit/ogr#478]
Change all exceptions that are raised for an unsupported feature to `OperationNotSupported` (from the default `NotImplementedError`)

closer info: https://github.com/packit/ogr/pull/477#discussion_r503077265

**Comment by lachmanfrantisek** [comment]
Just to make it clear:
We are speaking about methods that we can't implement because of the missing API on the git-forge side (e.g. Github/Pagure).

As an example, `GitHub` can't create private/confidential issues or `Pagure` can't comment on commits.

---

The abstract classes and the methods we haven't implemented yet should still have `NotImplementedError`.

**Comment by lachmanfrantisek** [comment]
Still valid.

**Comment by lachmanfrantisek** [comment]
This is easy! A really nice good-first-issue that is easy to do but require going through the code.

**Comment by lachmanfrantisek** [comment]
Ping sync to Jira.

**Comment by lachmanfrantisek** [comment]
Ping sync to Jira.
