### ISSUE TITLE
Adding assignees for issue that already exists

### ISSUE THREAD

**Issue by KPostOffice** [packit/ogr#586]
Hi all!

Really enjoying working with `ogr`. Would it be possible to add the functionality to add assignees to an issue which already exists?

Refs:
* https://docs.github.com/en/rest/reference/issues#add-assignees-to-an-issue
* https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html#github.Issue.Issue.add_to_assignees
* attached issue shows how to add assignee for GitLab
* https://src.fedoraproject.org/api/0/#issues-tab

See also: https://github.com/packit/ogr/pull/487

**Comment by lachmanfrantisek** [comment]
Hi @KPostOffice, glad you find `ogr` useful!

That's a valid feature request and not hard to implement.

Since you've already linked the documentation and gone through the code, will you be interested in contributing this? (We can help you with that.) Otherwise, I can't tell you an approximation of when this will be ready.

Regarding the implementation, we need to:
* [ ] Add the abstract `add_assignee` method to the `Issue` class:
    * https://packit.github.io/ogr/abstract.html#ogr.abstract.Issue
    * https://github.com/packit/ogr/blob/main/ogr/abstract.py#L139
* [ ] Implement the method for `Github`/`GitLab`/`Pagure`.
* [ ] Add tests for this (https://github.com/packit/ogr/blob/main/CONTRIBUTING.md#testing).

**Comment by KPostOffice** [comment]
Yeah, I can contribute this. It seems pretty straight forward. :+1:
