### ISSUE TITLE
Support creating a fork to an organization on GitHub or groups on GitLab

### ISSUE THREAD

**Issue by KPostOffice** [packit/ogr#631]
Both GitLab and GitHub support namespaces that don't belong to particular users - groups on GitLab and organizations on GitHub. I want to be able to fork to these namespaces if the authenticated user has the correct permissions.

**Comment by lachmanfrantisek** [comment]
@KPostOffice that's a really good suggestion. I'm a bit surprised we don't have it already. Are you also interested in taking a look at this and send a pull request?

**Comment by jpopelka** [comment]
I had a similar idea. I took it from the wrong end in #621, but there are at least some useful notes in https://github.com/packit/ogr/pull/621#issuecomment-891988079

**Comment by mfocko** [comment]
I might reopen it on Friday, since it's done at least for GitLab.

@jpopelka I think the notes are most helpful for your use-case in _hardly_, now I'm not really sure if it's usable at all in _ogr_, since it handles that specific use-case quite well, but would be more of PITA from the user-perspective :thinking:

On the other hand it might be beneficial to have the managers (that keep preferences of namespaces), but support **just one** namespace in the API, proposal:

1. reopen PR / cherry-pick / _whatever_
2. add optional parameter that specifies namespace where to fork
   - GitLab: needs to be adjusted
   - GitHub: needs to be done
   - Pagure: not supported
3. also implement the managers, since it fits usage in our projects
   - needs to be done for both GitHub & GitLab

If there are no more suggestions or issues with it, I will update the description with task list

**Comment by KPostOffice** [comment]
@lachmanfrantisek I'm not able to look at it this week but if no one has picked it up I can start looking at it next week. I think @mfocko has the right idea of extending `create_fork` with an optional `namespace` param

**Comment by KPostOffice** [comment]
For my use case I was just going to call the underlying PyGithub API, but they also don't support this functionality for some reason. I've opened an issue there as well. https://github.com/PyGithub/PyGithub/issues/2033

**Comment by mfocko** [comment]
@KPostOffice it's just under the `Repository.create_fork`, I guess that method you mentioned is for creating forks **specifically** in user's namespace 🤷‍♂️
