### ISSUE TITLE
Get Username GitHub

### ISSUE THREAD

**Issue by KPostOffice** [packit/ogr#660]
I was trying to get the username of the user of the service, but I was getting an error: `NoneType has no attribute get_username()`. I traced back through the code and I found this line in the GitHub authentication. Is there anyway to get this functionality ported to the github_app?

https://github.com/packit/ogr/blob/dd0c6fb7ca87cbdc36da7f7e2f2f510a8ebf0a7c/ogr/services/github/auth_providers/github_app.py#L64

My related issue https://github.com/thoth-station/support/issues/140

**Comment by TomasTomecek** [comment]
Gotta say I'm lost when I look at the traceback in the linked issue:
```
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/user.py", line 26, in get_username
    return self.service.github.get_user().login
AttributeError: 'NoneType' object has no attribute 'get_user'
```

Could you please share the code of thoth_advise.py where the ogr code is being invoked?

**Comment by KPostOffice** [comment]
Yeah, this isn't the exact line as the content of the file has changed, but the same issue will arise on this line:
https://github.com/thoth-station/kebechet/blob/08c9089a644e9ce04e857ae13a8be0f55dca62d2/kebechet/managers/thoth_advise/thoth_advise.py#L435

The short explanation is this (specifically for GitHub): 
`service.user.get_username()` calls the `get_username()` method of GitHubUser. The `get_username` method just returns `user.service.github.get_user().login`. `user.service.github` returns the following `self.authentication.pygithub_instance`; however for GitApp (and tokman) authentication this returns `None`. So the line in `get_username` goes from `user.service.github.get_user().login` -> `None.get_user().login`

**Comment by TomasTomecek** [comment]
I just returned from my long year-end recharge, thank you for the detailed analysis.

Are you still having the issue or were you able to figure it out in the meantime?

**Comment by mfocko** [comment]
I think I have run into this issue too… The problem is that `PyGithub` provides separate class for acquiring installations via GitHub App (you get unique token for each repository of the app, with expiry **and** at most 1 can be active at the same time). The thing is that you use those objects to query GitHub and they are tied to the repositories. So you cannot query `whoami` without having one of those objects **and** you cannot _guess_ the repository to get it, because you need to have an installation.

However I can see `.create_jwt()` method in the interface of that class providing instances. In my opinion the tokens behave in the same exact way (at most 1 at the same time and they expire (default seems to be 60 s)). For the purposes of `whoami` it should do, but it introduces, once again, race condition in the code, e.g. 2 workers running as the same app and querying for the login at the same time.

It's one line change that I've already done, I just need to test it.

**Comment by KPostOffice** [comment]
@mfocko Where is the limit on having one token active specified?

**Comment by mfocko** [comment]
@KPostOffice Closest thing I have found is this: https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app (but it only mentions that the tokens are valid for 1 hour)

Lemme double check if the part about one token.
